<?php

namespace vuelte\assets;

use Yii;
use yii\web\View;
use yii\web\AssetBundle;

/**
 * Main backend application asset bundle.
 */
class VueAsset extends AssetBundle
{
    public $sourcePath = __DIR__.'/resource/vue';
    public $css = [];
    public $js = [
        //'https://unpkg.com/vue/dist/vue.js',
        //'https://unpkg.com/vuex@3.0.1/dist/vuex.js',
        'vue.js',
        'vuex.js',
    ];
    public $jsOptions = [
        'position' => \yii\web\View::POS_HEAD
    ];
    public $cssOptions = [
        'position' => \yii\web\View::POS_HEAD
    ];
    public $depends = [];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        //$this->registerFormSubmitJs($this);
    }

    public function registerAssetFiles($view)
    {
        //parent
        parent::registerAssetFiles($view); // TODO: Change the autogenerated stub

        //submit form js
        $request = Yii::$app->getRequest();
        $js[] = "function YiiFormSubmit(data,formName){";
        $js[] = "var form = new formSubmit();";
        $js[] = "form.setFormName(formName);";
        $js[] = "form.setCsrfEnable(".($request->enableCsrfValidation?"true":"false").");";
        $js[] = "form.setCsrfParam('".$request->csrfParam."');";
        $js[] = "form.setCsrfToken('".$request->getCsrfToken()."');";
        $js[] = "form.submit(data);";
        $js[] = "}";

        //register js
        $view->registerJs(implode("",$js),View::POS_HEAD);
    }
}