<?php
namespace vuelte\widgets;

use Yii;
use yii\web\View;
use yii\helpers\Html;
use yii\base\InvalidCallException;

class ActiveElementForm extends \yii\widgets\ActiveForm
{
    /**
     * init
     */
    function init()
    {
        if (!isset($this->fieldConfig['class']))
            $this->fieldConfig['class'] = ActiveElementField::className();

        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * run
     */
    function run()
    {
        if (!empty($this->_fields)) {
            throw new InvalidCallException('Each beginField() should have a matching endField() call.');
        }

        //获取内容
        $content = ob_get_clean();

        //创建el-from标签
        $options = array_merge($this->options,[
            "method" => $this->method
        ]);
        echo Html::beginTag("el-form", $options);

        //输出内容
        echo $content;

        //结束el-from标签
        echo Html::endTag("el-form");
    }

    /**
     * @param $model
     * @param $attribute
     * @return string
     */
    static public function getFieldName($model,$attribute){
        return Html::getInputName($model, $attribute);
    }

    /**
     * @param $model
     * @param $attribute
     * @return string
     */
    static public function getFieldLabel($model,$attribute){
        return Html::encode($model->getAttributeLabel($attribute));
    }

    /**
     * @param $model
     * @param $attribute
     * @return mixed
     */
    static public function getFieldError($model,$attribute){
        return $model->getFirstError($attribute);
    }
}
?>